# Generated by Django 5.2.8 on 2025-11-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cloudtable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(default='user@cloud.com', max_length=50)),
                ('mob', models.CharField(max_length=10, unique=True)),
            ],
        ),
    ]
