# Generated by Django 5.2.8 on 2025-11-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('env_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cloudtable',
            old_name='mob',
            new_name='mobile',
        ),
    ]
