# Generated by Django 5.2.8 on 2025-11-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('env_app', '0002_rename_mob_cloudtable_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudtable',
            name='photo',
            field=models.URLField(default='empty'),
        ),
    ]
